include ../Makefile.param



########### SRCS & INC ############
SMP_SRCS := $(wildcard $(PWD)/*.c)

TARGET := v02_changemodule

TARGET_PATH := $(PWD)

# compile linux or LITEOS
include $(PWD)/../$(ARM_ARCH)_$(OSTYPE).mak

